config:
  bootstrap_expect: 3
  primary_datacenter: dc1
  acl:
    enabled: '{{ enabled|bool }}'
    default_policy: 'deny'
    down_policy: 'extend-cache'
    tokens:
      master: '{{ master_token }}'
      agent: '{{ agent_token }}'
  data_dir: /tmp
  retry_join:
    - 'provider=aws tag_key=Environment tag_value=dev'

acl_field: master
